apiVersion: v1
kind: Service
metadata:
  name: mongodb-shardX-service
  labels:
    name: mongodb-shardX
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb-shardX
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod-shardX
spec:
  serviceName: mongodb-shardX-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shardX
        tier: maindb
        replicaset: ShardXRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - ShardXRepSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: "test-ssd"
          hostPath:
            path: "/mnt/disks/ssd0"
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      containers:
        - name: mongod-shardX-container
          image: mongo
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--port"
            - "27017"
            - "--wiredTigerCacheSizeGB"
            - "0.25"
            - "--bind_ip"
            - "0.0.0.0"
            - "--shardsvr"
            - "--replSet"
            - "ShardXRepSet"
          resources:
            requests:
              cpu: 1.0
              memory: 3072Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: "test-ssd"

